### ISSUE TITLE
Unable to run the spark job

### ISSUE THREAD

**Issue by napsterdiggi** [aws-samples/amazon-eks-apache-spark-etl-sample#1]
I am trying to run a modified code taken from https://github.com/aws-samples/amazon-eks-apache-spark-etl-sample.

I was able to do most of the the steps successfully. However , getting below error while submitting my spark job.

"Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources"

Any help will be he highly appreciated.

**Comment by vgkowski** [comment]
Can you check the EKS cluster has enough resources to run Spark executors?

**Comment by vgkowski** [comment]
no answer from the requester
