### ISSUE TITLE
Docker build is failing 

### ISSUE THREAD

**Issue by Rajaneeshs** [aws-samples/amazon-eks-apache-spark-etl-sample#3]
While running docker build `docker build --target=spark -t <MY_DOCKER_REPO>/spark:v2.4.4` Its failing at 
`RUN curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb && dpkg -i sbt-$SBT_VERSION.deb && rm sbt-$SBT_VERSION.deb && apt-get update && apt-get install sbt && sbt sbtVersion && mkdir project && echo "scalaVersion := \"${SCALA_VERSION}\"" > build.sbt && echo "sbt.version=${SBT_VERSION}" > project/build.properties && echo "case object Temp" > Temp.scala && sbt compile && rm -r project && rm build.sbt && rm Temp.scala && rm -r target && mkdir -p /spark/ && curl -fsL https://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz | tar xfz - -C /spark/ && rm /spark/spark-2.4.4-bin-hadoop2.7/jars/kubernetes-*-4.1.2.jar && wget https://repo1.maven.org/maven2/io/fabric8/kubernetes-model-common/4.4.2/kubernetes-model-common-4.4.2.jar -P /spark/spark-2.4.4-bin-hadoop2.7/jars/ && wget https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/4.4.2/kubernetes-client-4.4.2.jar -P /spark/spark-2.4.4-bin-hadoop2.7/jars/ && wget https://repo1.maven.org/maven2/io/fabric8/kubernetes-model/4.4.2/kubernetes-model-4.4.2.jar -P /spark/spark-2.4.4-bin-hadoop2.7/jars/` 

with below error 
[info] Non-compiled module 'compiler-bridge_2.11' for Scala 2.11.12. Compiling...
/usr/share/sbt/bin/sbt-launch-lib.bash: line 59:   476 Killed                  "$@"
The command '/bin/sh -c curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb && dpkg -i sbt-$SBT_VERSION.deb && rm sbt-$SBT_VERSION.deb && apt-get update && apt-get install sbt && sbt sbtVersion && mkdir project && echo "scalaVersion := \"${SCALA_VERSION}\"" > build.sbt && echo "sbt.version=${SBT_VERSION}" > project/build.properties && echo "case object Temp" > Temp.scala && sbt compile && rm -r project && rm build.sbt && rm Temp.scala && rm -r target && mkdir -p /spark/ && curl -fsL https://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz | tar xfz - -C /spark/ && rm /spark/spark-2.4.4-bin-hadoop2.7/jars/kubernetes-*-4.1.2.jar && wget https://repo1.maven.org/maven2/io/fabric8/kubernetes-model-common/4.4.2/kubernetes-model-common-4.4.2.jar -P /spark/spark-2.4.4-bin-hadoop2.7/jars/ && wget https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/4.4.2/kubernetes-client-4.4.2.jar -P /spark/spark-2.4.4-bin-hadoop2.7/jars/ && wget https://repo1.maven.org/maven2/io/fabric8/kubernetes-model/4.4.2/kubernetes-model-4.4.2.jar -P /spark/spark-2.4.4-bin-hadoop2.7/jars/' returned a non-zero code: 137

**Comment by vgkowski** [comment]
Closing this. The docker build is working (retested it today). Your error is probably due to a lack of memory for your docker process.
