### ISSUE TITLE
Spark driver fails to start:  MountVolume.SetUp failed for volume "spark-conf-volume" : configmap "spark-on-eks-1616738080028-driver-conf-map" not foun

### ISSUE THREAD

**Issue by rehantahir** [aws-samples/amazon-eks-apache-spark-etl-sample#4]
[ec2-user@ip-10-0-2-213 kubernetes]$ kt describe po spark-on-eks-1616738080028-driver
Name:         spark-on-eks-1616738080028-driver
Namespace:    default
Priority:     0
Node:         ip-10-0-7-134....
Start Time:   Fri, 26 Mar 2021 05:54:41 +0000
Labels:       spark-app-selector=spark-b02c2fc9d748406591b4caf9793bb225
              spark-role=driver
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Failed
IP:           10.0.6.3
IPs:
  IP:  10.0.6.3
Containers:
  spark-kubernetes-driver:
    Container ID:  docker://3bd36f595470bb10d696f3f6349e0af2e944049aadec21041368153acdee58e4
    Image:         .....
    Image ID:      docker-pullable://.....
    Ports:         7078/TCP, 7079/TCP, 4040/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      driver
      --properties-file
      /opt/spark/conf/spark.properties
      --class
      ValueZones
      spark-internal
      s3a://nyc-tlc/trip data/yellow_tripdata_2018*.csv
      s3a://nyc-tlc/trip data/green_tripdata_2018*.csv
      s3a://nyc-tlc/misc/taxi _zone_lookup.csv
      s3a://......
    State:          Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "driver": executable file not found in $PATH: unknown
      Exit Code:    127
      Started:      Fri, 26 Mar 2021 05:54:49 +0000
      Finished:     Fri, 26 Mar 2021 05:54:49 +0000
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  1408Mi
    Requests:
      cpu:     1
      memory:  1408Mi
    Environment:
      SPARK_DRIVER_BIND_ADDRESS:   (v1:status.podIP)
      SPARK_LOCAL_DIRS:           /var/data/spark-4a558072-d8bd-40cc-b3c3-93109ea2b6e6
      SPARK_CONF_DIR:             /opt/spark/conf
    Mounts:
      /opt/spark/conf from spark-conf-volume (rw)
      /var/data/spark-4a558072-d8bd-40cc-b3c3-93109ea2b6e6 from spark-local-dir-1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from spark-token-7k9f9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  spark-local-dir-1:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  spark-conf-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      spark-on-eks-1616738080028-driver-conf-map
    Optional:  false
  spark-token-7k9f9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  spark-token-7k9f9
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age   From               Message
  ----     ------       ----  ----               -------
  Normal   Scheduled    40m   default-scheduler  Successfully assigned default/spark-on-eks-1616738080028-driver to ip-10-0-7-134.us-west-2.compute.internal
  Warning  FailedMount  40m   kubelet            MountVolume.SetUp failed for volume "spark-conf-volume" : configmap "spark-on-eks-1616738080028-driver-conf-map" not found
  Normal   Pulling      40m   kubelet            Pulling image "....:spkapp"
  Normal   Pulled       40m   kubelet            Successfully pulled image "....:spkapp" in 6.824614979s
  Normal   Created      40m   kubelet            Created container spark-kubernetes-driver
  Warning  Failed       40m   kubelet            Error: failed to start container "spark-kubernetes-driver": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "driver": executable file not found in $PATH: unk

**Comment by vgkowski** [comment]
Not able to reproduce
